### ISSUE TITLE
[ADSR Support] Misc changes from spreadsheet

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#16]
Reference document - https://docs.google.com/spreadsheets/d/1fj4eTPrnqi7n6H2DjhzBiviDVrDE1b5j/edit#gid=1141700887

- [x] Question whom are you staying with to be second in sequence

- [ ] Show BMI greater than 25 in Red

- [ ] Question “Going to school” to be hidden in baseline and endline if the Adolescent is already marked as dropped out in any of the previous encounters

- [ ] In the question for When the adolescent has left the school, only provide the option to select a year 

- [x] If parents are not alive has been answered in the baseline, hide questions related to parents occupation in subsequent forms

- [x] Program Summary - only keep Sickle cell result, remove Sickle cell disease option 

- [x] Baseline is getting scheduled again on editing enrolment

**Comment by Gojo-Taqi** [comment]
@salilsamanvay @nupoorkhandelwal for the second point(Show BMI greater than 25 in Red), it already shows in red in baseline and in endline. Was the requirement to show in program summary?
If yes, then that is not possible because we are concatenating the encounterDateTime along with the value as well.
