### ISSUE TITLE
[Adolescent Sewa Rural]: Program Summary & Decision Rule - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#58]
- [x] Make these changes in UAT in both endline and baseline form.
- [x] [Program Summary & Decision Rule](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=361752874)

**Comment by Dinesh2019** [comment]
As discussed with Sachin and vedant in the summary decision it will display the unique values since Nutritional status as per WHO is duplicated it is not displayed 

<img width="342" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9oQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--143ca7cf9566c8b26fb06671025665ee1ba20185/Screenshot%202024-05-30%20at%2011.23.03%E2%80%AFAM.png" alt="Screenshot 2024-05-30 at 11.23.03 AM.png" />
